### ISSUE TITLE
button.user.js not working with redacted.ch (new PTH domain)

### ISSUE THREAD

**Issue by peioe** [jimrollenhagen/pywhatauto#38]
When trying to use button.user.js with redacted.ch (PTH's new name/domain), after adding the url to the list in the script, you get:
![screenshot_2017-02-21_17-36-32](https://cloud.githubusercontent.com/assets/17990655/23174333/4d289b7a-f85c-11e6-8e05-76d0312966cc.png)

**Comment by SavageCore** [comment]
Check your script against [this](https://github.com/SavageCore/pywhatauto/blob/redacted/button.user.js) until my PR is merged. Should work fine.

**Comment by peioe** [comment]
that works, thanks :)

**Comment by jimrollenhagen** [comment]
\o/
