### ISSUE TITLE
regex filter not working

### ISSUE THREAD

**Issue by kplimack** [jimrollenhagen/pywhatauto#45]
this one is straight from the example...

```
05/28-16:30:56 INFO    redacted **** Announce found: Umphrey's McGee - 2017-05-26 Summer Camp Chillicothe, IL [2017] [Concert Recording] - MP3 / V0 (VBR) / WEB - https://redacted.ch/torrents.php?id=535502 / https://redacted.ch/torrents.php?action=download&id=1127042 - progressive.rock, jam.band
05/28-16:30:56 FILTER  redacted This is a(n) music release
05/28-16:30:56 FILTER  redacted Checking filter section 'WHAT-JAMS'
05/28-16:30:56 FILTER  redacted Detected format match using 'MP3' in MP3
05/28-16:30:56 DEBUG   redacted Didn't detect artist match using 'Umphrey(.+)s McGee' in Umphrey's McGee
```

**Comment by kplimack** [comment]
@jimrollenhagen are you still supporting this project?  if not, can you add me as a collaborator or transfer the project to me and I'll take over?

**Comment by jimrollenhagen** [comment]
@kplimack yes, I still support it, just haven't been online much to look at it lately.

Can you post your filters here?

**Comment by jimrollenhagen** [comment]
Sorry, overlooked the "from the example" bit. There's special syntax to use regex... let me look it up and fix the example.

**Comment by jimrollenhagen** [comment]
Fixed the readme in https://github.com/jimrollenhagen/pywhatauto/commit/7823a73e5272bc78955df6ddabbeb6d4b13515f0

Regex filters need a prefix of `@`. Sorry for the confusion!

**Comment by jimrollenhagen** [comment]
@kplimack please do close this if it works for you :)

**Comment by kplimack** [comment]
@jimrollenhagen ill try when i get home, but i had put in `umphrey's mcgee` without escaping or regex and it seems to be matching now, it just feels unsafe, so i'll try this out later, for sure
