### ISSUE TITLE
The new settings page for the userscript is awful

### ISSUE THREAD

**Issue by peioe** [jimrollenhagen/pywhatauto#46]
1. it was perfectly fine before, and it's not obvious at all you have to go the settings page of a tracker to change options. I was pretty confused trying to find the line I had to edit in the script
2. I can't use it because I'm using a reverse proxy and the url i need to create is https://user:password@domain.tld/pywa/dl.pywa?pass=password etc

**Comment by SavageCore** [comment]
Regarding point 1 it should display a pop up notification alerting you to configure the script when settings are missing. Perhaps better wording is needed.

As for custom links I could add another option field which would take a full URL up to `dl.pywa?pass=` and/or have it configurable within the script again.

Having both a line like before in the script and settings page is nice for non gazelle sites...

Thoughts @jimrollenhagen ?

**Comment by jimrollenhagen** [comment]
@SavageCore I'm good with that :)

**Comment by SavageCore** [comment]
There we go @peioe you can take the userscript from my branch until merged

Decided to add the weblink line back so either takes effect now.

**Comment by peioe** [comment]
thanks :)

**Comment by jimrollenhagen** [comment]
This is merged now, sorry for the wait! Thanks as always @SavageCore :)
