### ISSUE TITLE
bot not responding to commands

### ISSUE THREAD

**Issue by apiontek** [jimrollenhagen/pywhatauto#48]
Running 1.74 from git, I did a server update & reboot and suddenly noticed the bot is no longer responding to commands. I'm using it on two IRC servers. It's not responsive on either. It was responsive just a couple days ago. Server updates only included git updates, it seems.

I run it as a service; when I run it manually to see the output, I can see it gets connected, and it sees release announcements, but when I /msg it %help or %stats or %current, I get no response, and I see nothing in the output.

Anyone else seeing this? How to begin troubleshooting?

**Comment by SavageCore** [comment]
Have you checked that `nickowner` is correct in `credentials.conf`? If you see the bot connect on IRC it sounds like it is ignoring you...

**Comment by apiontek** [comment]
This was the problem. My class updated on both trackers recently which changed my ident. I'll remember to watch for that in the future. Thanks!
