### ISSUE TITLE
button.user.js bugged for notwhat.cd

### ISSUE THREAD

**Issue by peioe** [jimrollenhagen/pywhatauto#58]
Hey

There is a bug in button.user.js when using it on notwhat.cd because the script sees it as *what.cd, which adds an incorrect site name to the link the script adds.

**Comment by dewey** [comment]
This is now fixed, just need someone to merge it!

**Comment by SavageCore** [comment]
I was going to do it by changing regex for what to `https?.*?(?:[^not])what\.cd.*` but this is probably better. Do we even need to keep what.cd in there?

**Comment by dewey** [comment]
> Do we even need to keep what.cd in there?
Legacy 😢
